
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telcel-ai-deployment
  labels:
    app: telcel-ai-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telcel-ai-app
  template:
    metadata:
      labels:
        app: telcel-ai-app
    spec:
      imagePullSecrets:
        - name: ocir-secret
      volumes:
        - name: oci-key
          configMap:
            name: oci-api-key-config
      containers:
        - name: telcel-ai-app
          image: mx-monterrey-1.ocir.io/axrmvrmnextg/orion-telcel-ai-app:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: oci-key
              mountPath: /app/.oci
              readOnly: true
          env:
            # OCI - no sensibles, se dejan como valor plano
            - name: OCI_GENAI_ENDPOINT
              value: "https://inference.generativeai.us-chicago-1.oci.oraclecloud.com"
            - name: OCI_REGION
              value: "us-chicago-1"
            - name: OCI_MODEL_ID
              value: "google.gemini-2.5-flash"
            - name: OCI_SERVICE_ENDPOINT
              value: "https://inference.generativeai.us-chicago-1.oci.oraclecloud.com"
            - name: OCI_COMPARTMENT_ID
              value: "ocid1.compartment.oc1..aaaaaaaas4ruomqblntlmwt76xqkam4efboqcvlnae3o5m22ao4ja4en5ooa"
            - name: OCI_USER
              value: "ocid1.user.oc1..aaaaaaaahlpvonwo7kosxnyamrgu2mmh5ykwnzqz4rtxu5cwsphj2efddx7a"
            - name: OCI_TENANCY
              value: "ocid1.tenancy.oc1..aaaaaaaap5s754zivtxd3uwmpoflh3wpgily2tsnerjys4fx55mxp7ahn6kq"
            - name: OCI_FINGERPRINT
              value: "8e:64:9f:d0:bc:46:1b:25:0c:ca:f0:60:98:91:34:d4"
            - name: OCI_KEY_FILE
              value: "/app/.oci/oci_api_key.pem"
            - name: OCI_ENABLE_STREAMING
              value: "False"
            # LLM
            - name: LLM_TEMPERATURE
              value: "0.3"
            - name: LLM_MAX_TOKENS
              value: "600"
            # PostgreSQL / sesiones
            - name: DATABASE_URL
              value: "postgresql://pgadmin:Or4#D3Sytem-@10.0.10.166:5432/reni_agent"
            - name: SESSION_TTL_HOURS
              value: "24"
            # Redis
            - name: REDIS_HOST
              value: "aaauwo7dsya3u3vi5yvwqeuzv6uh646zwukqjru7nrnpr2hy4xqgznq-p.redis.us-chicago-1.oci.oraclecloud.com"
            - name: REDIS_PORT
              value: "6379"
            # Oracle NoSQL
            - name: NOSQL_TABLE
              value: "orion_telcel_ai_conversations"
            - name: NOSQL_REGION
              value: "us-chicago-1"
            # Object Storage
            - name: OBJECT_BUCKET
              value: "orion-telcel-ai-bucket"
            - name: OBJECT_NAMESPACE
              value: "idkrobdezpcz"
            # OpenAI
            - name: OPENAI_API_KEY
              value: "sk-xxxx"
            - name: OPENAI_MODEL
              value: "gpt-4o-mini"
            - name: TEMPERATURE
              value: "0"
            # CSV
            - name: CSV_PATH
              value: "docs/csv/Masivo_clientes.csv"
            # WhatsApp
            - name: WHATSAPP_ACCESS_TOKEN
              value: "EAAMzCzdUfw4BQ08YVaZABaahKqZAZCBZAZAqFlbnVZC3pwt9mFUqwweTQYZBQChIPBAltF9ue05DS4InZAJLVZA89uzzEDnE5PWotBMq62dcSqBAK4oNaI4c2XUGY1uwdbj5HVVw41fKIfbsvpreQQt8sCM3nnK8iLdF5XVYvUbhq93tJEssM5AVulGvwY2IcgVbyNwZDZD"
            - name: WHATSAPP_PHONE_NUMBER_ID
              value: "1035233273006117"
            - name: WHATSAPP_API_VERSION
              value: "v22.0"
            - name: VERIFY_TOKEN
              value: "17enoc17"
            - name: WHATSAPP_URL
              value: "https://graph.facebook.com/v22.0"
            # LangChain
            - name: LANGCHAIN_TRACING_V2
              value: "true"
            - name: LANGSMITH_API_KEY
              value: "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"
            # Private / auth
            - name: PRIVATE_KEY
              value: "LfBchliYEiCZhnkS_TbJjZXBRHs0pLSA6ZBtlheMQ8Y="
            - name: ACCESS_SECRET_KEY
              value: "Agal8iL6r5I26rweXXza0K4BQXhx6PLvwfdpy_w76H8"
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "30"
            - name: API_KEY
              value: "zvDQevdVVrijrczOGUc4fRJ0ZC6h-yHfF7ZZgsK8hZY"
            # Templates
            - name: TEMPLATE_ULTRA
              value: "template_libre"
            - name: TEMPLATE_LIBRE
              value: "template_ultra"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: telcel-ai-service
  namespace: default
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
    oci-network-load-balancer.oraclecloud.com/internal: "true"
    oci-network-load-balancer.oraclecloud.com/subnet: "ocid1.subnet.oc1.mx-monterrey-1.aaaaaaaaihh6ja6hhvh4nzujzrcerdv3ik5qk5vrkzjzpzxl7bfxuezidtea"
spec:
  type: LoadBalancer
  selector:
    app: telcel-ai-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
